<a href="https://colab.research.google.com/github/manaswinialakunta08/machine-learning/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#to import dataset
data_set=pd.read_csv('/content/user_datacsv__2026_06_12_12_31_57 (3).csv')
print(data_set)


      Userid   Gender  Age  Est_salary  Purchased
0   15810944     Male   35       20000          0
1   15668575   Female   26       43000          0
2   15603246  Fema le   27       57000          0
3   15804002     Male   19       76000          0
4   15728773     Male   27       58000          0
5   15598044  Fema le   27       84000          0
6   15694829  Fema le   32      150000          1
7   15600575     Male   25       33000          0
8   15727311  Fema le   35       65000          0
9   15570769  Fema le   26       80000          0
10  15606274  Fema le   26       52000          0
11  15746139     Male   20       86000          0
12  15704987     Male   32       18000          0
13  15628972     Male   18       82000          0
14  15697686     Male   29       80000          0
15  15733883     Male   47       25000          1
16  15617482     Male   45       26000          1
17  15704583     Male   46       28000          1
18  15621083  Fema le   48       29000          1


In [2]:
#independent variables
x=data_set.iloc[:,[2,3]].values
print(x)


[[    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]]


In [3]:
#dependent variables
y=data_set.iloc[:,4].values
print(y)


[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1]


In [6]:
#splitting the data set into trainig and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.25,
    random_state=0
)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[    29  80000]
 [    48  29000]
 [    32 150000]
 [    45  22000]
 [    27  58000]
 [    27  57000]
 [    27  84000]
 [    45  26000]
 [    26  80000]
 [    25  33000]
 [    46  28000]
 [    19  76000]
 [    35  20000]
 [    47  25000]
 [    32  18000]]
[[   35 65000]
 [   18 82000]
 [   47 49000]
 [   26 43000]
 [   20 86000]
 [   26 52000]]
[0 1 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 0 1 0 0 0]


In [7]:
#feature scaling
from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
x_train=st_x.fit_transform(x_train)
x_test=st_x.transform(x_test)
print(x_train)
print(x_test)


[[-0.53667349  0.77998889]
 [ 1.50268577 -0.66129493]
 [-0.2146694   2.75822159]
 [ 1.18068167 -0.8591182 ]
 [-0.75134288  0.15825862]
 [-0.75134288  0.12999815]
 [-0.75134288  0.89303076]
 [ 1.18068167 -0.74607633]
 [-0.85867758  0.77998889]
 [-0.96601228 -0.54825306]
 [ 1.28801637 -0.6895554 ]
 [-1.61002047  0.66694702]
 [ 0.1073347  -0.91563913]
 [ 1.39535107 -0.7743368 ]
 [-0.2146694  -0.97216007]]
[[ 0.1073347   0.35608189]
 [-1.71735516  0.83650983]
 [ 1.39535107 -0.09608559]
 [-0.85867758 -0.26564839]
 [-1.50268577  0.9495517 ]
 [-0.85867758 -0.01130419]]


In [13]:
#creating svm classifier
from sklearn.svm import SVC
from sklearn.svm import SVC

classifier = SVC(
    kernel="linear",
    random_state=0
)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)


[0 0 1 0 0 0]


In [14]:
#creating confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[5 0]
 [0 1]]


In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

1.0
